FROM jenkins/agent:jdk21

USER root

RUN mkdir -p /root/jenkins
WORKDIR /root/jenkins

RUN apt update -y \
    && apt upgrade -y \
    && apt install -y \
    python3-pip \
    python3-dev \
    python3-venv \
    ansible \
    && python3 -m venv /venv \
    && /venv/bin/pip3 install --no-cache-dir --default-timeout=100 --retries=10 \
    stevedore \
    jenkins-job-builder

RUN /venv/bin/pip3 install setuptools==69.5.1

ENV PATH="$PATH:/venv/bin"

RUN curl -fsSL https://get.docker.com | sh